languageCode = "en-us"
title = "Gustavo Lichti"
baseurl = "http://lichti.com.br/"
theme = "hugo-theme-nix"
[params]
  GithubID = "lichti"
  TwitterID = "lichti"
  LinkedInID = "gustavo-lichti"
  FacebookID = "gustavo.lichti"
  Name = "Gustavo Lichti"
  HeaderUsername = "Gustavo"
  HeaderHostname = "Lichti"
  Email = "gustavo@lichti.com.br"
  About = "Apaixonado por tecnologia, entusiasta do código aberto, hardworker, usuário diário de linux desde 2002. Experiência de 14 anos na área de Tecnologia da Informação, com foco em sistemas e infraestrutura."
  ProfilePicture = "me.jpg"
  #GoogleAnalytics = "your_google_analytics_id"